export const sponsorList = [
  {
    name: "BAE Systems",
    fileName: "bae",
    url: "https://www.baesystems.com/en/home",
    id: 1,
  },
  {
    name: "Magellan Aerospace",
    fileName: "magellan",
    style: "bg-white",
    url: "https://magellan.aero/",
    id: 2,
  },
  {
    name: "Grainger",
    fileName: "grainger",
    url: "https://www.grainger.com/",
    style: "bg-white",
    id: 3,
  },
  {
    name: "Queens College",
    fileName: "qc",
    style: "bg-white",
    url: "https://www.qc.cuny.edu/",
    id: 4,
  },
  {
    name: "LMT Onsrud",
    fileName: "lmtonsrud",
    style: "bg-white",
    url: "https://www.onsrud.com/",
    id: 5,
  },
  {
    name: "GitHub",
    fileName: "github",
    style: "bg-white",
    url: "https://github.com/",
    id: 6,
  },
  {
    name: "THHS Alumni Association",
    fileName: "thhs",
    url: "https://thaa.org/",
    id: 7,
  },
  {
    name: "THHS PTA",
    fileName: "thhs",
    url: "https://www.thhs.qc.edu/apps/pages/pta",
    id: 8,
  },
  {
    name: "Consolidated Edison",
    fileName: "conEdison",
    url: "https://www.coned.com/en/",
    id: 9,
  },
  {
    name: "The Mu Family",
    fileName: "mufamily",
    id: 10,
  },
  {
    name: "Bloomberg",
    fileName: "bloomberg",
    style: "p-2 bg-white",
    url: "https://www.bloomberg.com/",
    id: 11,
  },
  {
    name: "Professional Steel Supply Co.",
    fileName: "professionalsteel",
    url: "https://www.thebluebook.com/iProView/810699/professional-steel-supply-corp/subcontractors/",
    id: 12,
  },
  {
    name: "NASA",
    fileName: "nasa",
    url: "https://www.nasa.gov/",
    id: 13,
  },
];
