export const mentorList = [
  {
    name: "Joel Heitman",
    title: "Head Coach",
    bio: "Mr. Heitman is the Head Coach of the Steel Hawks. He joined the Steel Hawks in 2013. His passion for Robotics has allowed the team to soar, and he hopes that with the help of his mentors, he can inspire the next generation of innovators.",
    fileName: "heitman",
    id: 1,
  },
  {
    name: "Susan Brustein",
    title: "Coach",
    bio: "Ms. Brustein is a Coach for the Steel Hawks. She was one of the founding coaches in 2008. Ms. Brustein is the Assistant Principal of Math, Science, and Technology at our school. She is currently the mentor of our Public Relations subteam.",
    fileName: "brustein",
    id: 2,
  },
  {
    name: "Joshua Raghunath",
    title: "Coach",
    bio: "Mr. Raghunath is a Coach for the Steel Hawks. He joined the Steel Hawks in September of 2014. As an AP Physics teacher, he helps team members apply what they learn in his class to build the most efficient robot. His background in finance helps team members learn how to develop the Steel Hawks brand and represent the team professionally.",
    fileName: "raghunath",
    id: 3,
  },
  {
    name: "David Stern",
    title: "Coach",
    bio: "Mr. Stern is a Coach for the Steel Hawks. He joined the Steel Hawks in September of 2016. As a Regents Physics teacher, he helps team members apply what they learn in class to their robot designs.",
    fileName: "stern",
    id: 4,
  },
  {
    name: "John Tsai",
    title: "Coach",
    bio: "Mr. Tsai is a coach for the Steel Hawks.",
    fileName: "tsai",
    id: 5,
  },
  {
    name: "Olan-Ray Frith",
    title: "Fabrication Mentor",
    bio: "Olan is the fabrication mentor for the Steel Hawks. He guides us through the prototyping, designing, and building processes.",
    fileName: "olan",
    id: 6,
  },
  {
    name: "Weijian Zeng",
    title: "Programming Mentor",
    bio: "Weijian is the programming mentor for the Steel Hawks. We are grateful for his work in helping aspiring software engineers develop clean, well-written code for the team.",
    fileName: "weijian",
    id: 7,
  },
  {
    name: "Kevin Goetzger & Kenneth Leuci",
    title: "Mentor",
    bio: "Kevin and Kenneth are mentors for the Steel Hawks. We are grateful for their work in creating the practice field that we use for Open Field Weekend.",
    fileName: "kevinken",
    id: 8,
  },
];
