export const robotData = [
  {
    year: "2022",
    name: "Hawktimus Prime",
    game: "Rapid React",
    fileNames: ["robot1", "robot2", "robot3"],
    bio: "Climb low, climb high, shoot low, shoot high, defend. Our robot has transformed to do it all, winning the 2022 New York Tech Valley Regional. ",
    type: "carousel",
    id: 0,
  },
  {
    year: "2022",
    name: "RI6H",
    game: "Rapid React",
    fileNames: [],
    bio: "Robot In 6 Hours. Hawktimus Prime got sent to Alabama during Worlds so we built a new one in six hours to compete with in case Hawktimus Prime didn't make it in time.",
    type: "img",
  },
  {
    name: "HyLo Wren",
    year: "2020",
    game: "Infinite Recharge",
    bio: "Image Missing :(",
    type: "",
    id: 1,
  },
  {
    year: "2019",
    name: "Cygnus",
    game: "Deep Space",
    fileNames: "2019",
    bio: "",
    type: "img",
    id: 2,
  },
  {
    year: "2018",
    name: "Steel Hawking",
    game: "Power Up!",
    fileNames: "2018",
    bio: "",
    type: "img",
    id: 3,
  },
  {
    year: "2017",
    name: "Aquila",
    game: "Steamworks",
    video: "https://www.youtube.com/embed/sIoXR36DF2A",
    bio: "Winner of 2017 Hudson Valley Regional.",
    type: "vid",
    id: 4,
  },
  {
    year: "2016",
    name: "Red Tail",
    game: "Stronghold",
    fileNames: "2016",
    bio: "",
    type: "img",
    id: 5,
  },
  {
    year: "2015",
    name: "Raptor",
    game: "Recycle Rush",
    video: "https://www.youtube.com/embed/EtHq5U6SAsg",
    bio: "",
    type: "vid",
    id: 6,
  },
  {
    year: "2014",
    name: "Tomahawk",
    game: "Aerial Assist",
    video: "https://www.youtube.com/embed/PXzYjObkA2A",
    bio: "",
    type: "vid",
    id: 7,
  },
];
